version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serverless
    versions:
    - 2.20.1
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.2
    - 2.28.0
    - 2.28.7
    - 2.29.0
    - 2.30.3
    - 2.31.0
    - 2.33.1
    - 2.35.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
