service: serverless-alexa-skill

plugins:
  - serverless-plugin-typescript
  - serverless-alexa-skills

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
      ALEXA_METRICS: ${env:AWS_ALEXA_FACTS_TABLENAME, 'Facts'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
      Resource:
        - "arn:aws:dynamodb:${env:AWS_REGION, 'us-east-1'}:${env:AWS_ACCOUNTID}:table/${env:AWS_ALEXA_FACTS_TABLENAME, 'Facts'}"
package:
  exclude:
    - node_modules/**

functions:
  alexa:
    handler: src/handler.alexa
    include:
      - src/**
    events:
      - alexaSkill

custom:
  alexa:
    vendorId: ${env:AMAZON_VENDOR_ID}
    clientId: ${env:AMAZON_CLIENT_ID}
    clientSecret: ${env:AMAZON_CLIENT_SECRET}
    skills:
      - id: ${env:ALEXA_SKILL_ID}
        manifest:
          publishingInformation:
            distributionCountries: [
              "US"
            ]
            isAvailableWorldwide: false
            testingInstructions: "Say 'Alexa, open ${env:ALEXA_SKILL_NAME}.'"
            locales:
              en-US:
                # TODO: Replace me
                name: ${env:ALEXA_SKILL_NAME}
                summary: "Insert a summary for your skill"
                examplePhrases: [
                  "Alexa, open ${env:ALEXA_SKILL_NAME}",
                  "Alexa, ask ${env:ALEXA_SKILL_NAME} how many...",
                  "Alexa, ask ${env:ALEXA_SKILL_NAME}...."
                ]
                description: "Alexa Skill that shares interesting facts about ${env:ALEXA_SKILL_NAME}"
          apis:
            custom:
              endpoint:
                uri: arn:aws:lambda:${env:AWS_REGION, 'us-east-1'}:${env:AWS_ACCOUNTID}:function:serverless-alexa-skill-${opt:stage, 'dev'}-alexa
          manifestVersion: '1.0'
        models:
          en-US:
            interactionModel:
              languageModel:
                invocationName: ${env:ALEXA_SKILL_NAME}
                intents:
                  - name: AMAZON.HelpIntent
                    samples: []
                  # TODO: Add Intent
                  # Example Below
                  # - name: MyMetricIntent
                  #   sample:
                  #     - tell me about my metric